# 1. The Database Connection (H2 In-Memory)
spring.datasource.url=jdbc:h2:file:./data/awshub_db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Hibernate/JPA Setup
# (This tells Hibernate to speak 'H2' instead of 'Postgres')
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# 3. H2 Console Activation
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# --- STRIPE PAYMENT GATEWAY ---
stripe.api.key=sk_test_51TMu4i9cwza92vUt7xbow4zWl2HU1duakQ6AGbYCZWp9SULgxeZwKuf8Z4TMPGo8piFh6Gi8nYYcKH4LdqvFvLqz008LUp3EIg
stripe.webhook.secret= whsec_f21a4eb11aa6924a39d48862bfb9e0b6de3485c9732b45d6f0cf0bbce0be78b8
